name: ElementSmp
version: '1.0-SNAPSHOT'
main: net.saturn.elementSmp.ElementSmp
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
commands:
  elements:
    description: View element info
  trust:
    description: Manage trust list
  element:
    description: Admin element commands
  mana:
    description: Manage mana
  util:
    description: Utility commands
  togglerecipe:
    description: Toggle recipes
  ability1:
    description: Use Ability 1
  ability2:
    description: Use Ability 2
